data_loader:
  name: "Texture"
  input_size: 64
  train_path: "datasets/mask_train_2"
  val_path: "datasets/mask_test_2"
  texture_path: "datasets/textures"
  train_on_textures: False
  crop: [7, 7]
  textures: [2]
train:
  model: "hierarchical_vae_7x7"
  padding: 3
  stride: 1
  kernel_size: [7, 7]
  model_params: 
      in_shape: [3, 64, 64]
      n_latent: 16
  little_vae_params:
    n_latent: 16
    in_shape: [3, 7, 7] 
    path: "models/texture_7x7_color/checkpoint_56.tar"
  loss_function: "vae_loss"
  loss_parameters:
  batch_size: 32
  latent_size: 16
  in_shape: [3, 64, 64]
  device: 'cuda:1'
  learning_rate: 0.0003
  num_epochs: 300
  save_as: "hierarchical_color_2"
  save_dir: "models/hierarchical_color_2"
  resume: False
