data_loader:
  name: "Texture"
  input_size: 64
  train_path: "datasets/mask_train"
  val_path: "datasets/mask_val"
  texture_path: "datasets/textures"
  train_on_textures: False
  crop: [5, 5] 
train:
  model: "vae_v2"
  padding: 3
  stride: 1
  kernel_size: [7, 7]
  model_params: 
      in_shape: [3, 64, 64]
      n_latent: 16
  loss_function: "vae_loss"
  loss_parameters:
  batch_size: 32
  latent_size: 16
  in_shape: [3, 64, 64]
  device: 'cuda:1'
  learning_rate: 0.0003
  num_epochs: 300
  save_as: "regular_vae"
  save_dir: "models/regular_vae"
  resume: False
